version: '2'

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code/
      - /code/node_modules/
    environment:
      - REACT_APP_API_URL=http://localhost:7712
    ports:
      - 7703:3000
